---
title: "figures"
author: "Katie Florko"
date: "12/07/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This script takes the plots made in Appendix 3 and formats, rearranges, and exports them as figures for the paper and supplemental material.

# Libraries
```{r}
library(ggplot2)
library(cowplot)
```



# Template
```{r}

p1 <- ggplot() + theme_minimal() +
  theme(axis.text = element_blank(),
        axis.title.x = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        text = element_text(size=14),
        strip.background = element_rect(colour = "white"),
        legend.position = c(0.86, 0.82), 
        legend.direction = "vertical", 
        legend.background = element_blank()) 
```


# Fig. 4
```{r}
fig4a <- p1 + 
  tidyterra::geom_spatraster(data = fish_raster) +
  scale_fill_viridis(option = "mako", limits = c(0.5, 0.75), breaks = c(0.5,0.6,0.7), name = "Prey\ndiversity") +
   geom_sf(data = nat_trans, fill = "grey80", color = "white") + 
   coord_sf(xlim = ext(fish_raster)[1:2], ylim = ext(fish_raster)[3:4], expand = F) +
  geom_point(data=seal, aes(x=lon, y=lat), size=1.75, alpha = 0.6, color = "#FCEEAE") + 
  geom_path(data=seal, aes(x=lon, y=lat), color = "#FCEEAE") +
  theme(legend.key.height=unit(0.3,"cm"),
        legend.key.width = unit(0.4, "cm"),
        legend.direction = "horizontal",
        legend.position = c(0.85, 0.86),
        text=element_text(size=16)) +
  ggtitle("D) Seal track") +
  ylab(" \n \n  ") + xlab("") +
  annotate("segment", x=-Inf, xend=Inf, y=-Inf, yend=-Inf, size = 1) +
  annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf, size = 1) +
  guides(fill = guide_colourbar(title.position="top", 
         title.hjust = 0.5), 
         size = guide_legend(title.position="top", title.hjust = 0.5))

data_hmm$state <- as.factor(momentuHMM::viterbi(hmm_trans_3))
# make sure data_hmm is the UTM version

fig4b <- p1 +
  scale_fill_viridis(option = "mako", limits = c(0.5, 0.75), name = "Prey\ndiversity") +
  geom_path(data=data_hmm, aes(x=x, y=y, color = state, group =ID)) + 
  geom_point(data=data_hmm, aes(x=x, y=y, color = state, shape = state), size=2, alpha = 0.8) + 
  scale_color_manual(values = c("#99DDB6", "#539D9C", "#312C66"), 
                     labels = c("Slow", "Moderate", "Fast"), 
                     name = "HMM state") +
  scale_shape_manual(values = c(15, 16, 17), 
                     labels=c("Slow", "Moderate", "Fast"), 
                     name = "HMM state") +
  geom_sf(data = nat_trans, fill = "grey80", color = "white") + 
  coord_sf(xlim = ext(fish_raster)[1:2], ylim = ext(fish_raster)[3:4], expand = F) +
  theme(legend.key.height=unit(0.3,"cm"),
        legend.key.width = unit(0.4, "cm"),
        legend.direction = "vertical",
        legend.position = c(0.2, 0.15),
        text=element_text(size=16)) +
  ggtitle("C) HMM decoded states") +
  ylab(" \n \n  ") + xlab("") +
  annotate("segment", x=-Inf, xend=Inf, y=-Inf, yend=-Inf, size = 1) +
  annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf, size = 1) +
  guides(fill = guide_colourbar(title.position="top", 
         title.hjust = 0.5), 
         size = guide_legend(title.position="top", title.hjust = 0.5))


fig4c <- p1 + 
  geom_sf(data = nat_trans, fill = "grey80", color = "white") + 
  coord_sf(xlim = ext(fish_raster)[1:2], ylim = ext(fish_raster)[3:4], expand = F) +
  geom_point(data=data_rsf, aes(x=x_, y=y_, color = case_), alpha = 0.8) +
  geom_path(data=seal, aes(x=lon, y=lat), color = "#5B207C") +
  scale_color_manual(values = c("#F1A97A", "#5B207C"), 
                     label = c("Available", "Observed"), name = "   Data type") +
  theme(legend.position = c(0.80, 0.89),
        text=element_text(size=16)) +
  ggtitle("A) RSF samples") +
  ylab(" \n \n  ") + xlab("") +
  annotate("segment", x=-Inf, xend=Inf, y=-Inf, yend=-Inf, size = 1) +
  annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf, size = 1) +
  guides(fill = guide_colourbar(title.position="top", 
         title.hjust = 0.5), 
         size = guide_legend(title.position="top", title.hjust = 0.5)) 

# make sure used points are on top of available points for viz
data_ssf <- data_ssf %>%
  mutate(case_ = factor(case_, levels = c("FALSE", "TRUE"))) 

fig4d <- p1 + 
  geom_point(data=data_ssf, aes(x=x2_, y=y2_, color = case_), alpha = 0.8) +
  geom_point(data=data_ssf %>% filter(case_ == "TRUE"), aes(x=x2_, y=y2_), alpha = 0.8, color = "#5B207C") +
  geom_path(data=seal, aes(x=lon, y=lat), color = "#5B207C") +
  scale_color_manual(values = c("#F1A97A", "#5B207C"), 
                     label = c("Available", "Observed"), 
                     breaks = c("FALSE", "TRUE"),
                     name = "   Data type") +
  geom_sf(data = nat_trans, fill = "grey80", color = "white") + 
  coord_sf(xlim = ext(fish_raster)[1:2], ylim = ext(fish_raster)[3:4], expand = F) +
  theme(legend.position = c(0.80, 0.89),
        text=element_text(size=16)) +
  ggtitle("B) SSF samples") +
  ylab(" \n \n  ") + xlab("") +
  annotate("segment", x=-Inf, xend=Inf, y=-Inf, yend=-Inf, size = 1) +
  annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf, size = 1) +
  guides(fill = guide_colourbar(title.position="top", 
         title.hjust = 0.5), 
         size = guide_legend(title.position="top", title.hjust = 0.5))

tiff(file = "figures/asus_fig4.tiff", units="in", width=8, height=9, res=500)
plot_grid(fig4c, fig4d, fig4b, fig4a,  ncol = 2)
dev.off()
```

# Fig. 5
```{r}
res_both <- dplyr::bind_rows(res1 %>% mutate(Model = "RSF"),
                      res2 %>% mutate(Model = "SSF")) %>%
  mutate(Model = as.factor(Model))

fig5a <- ggplot() + theme_minimal() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray") +
  geom_line(data = res_both, aes(x = preydiv_x1, y = log_rss, color = Model), size = 1, linetype = 2) +
  geom_ribbon(data = res_both, aes(y = log_rss, ymin=lwr, ymax=upr, x=preydiv_x1, fill = Model), alpha = 0.4) +
  scale_color_manual(values = c("#BE496F", "#F8D59F")) +
  scale_fill_manual(values = c("#BE496F", "#F8D59F")) +
  xlab("Prey diversity") +
  ylab("\nlog-RSS") +
  annotate("segment", x=-Inf, xend=Inf, y=-Inf, yend=-Inf, size = 1) +
  annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf, size = 1) +
  ggtitle("A)") +
  theme(legend.position = c(0.19, 0.9), text = element_text(size=14)) +
  xlim(0.55, 0.70) +
  ylim(-2.5, 2.5)

fig5b <- ggplot(results_ssf2, aes(x = preydiv_x1, y = (log_rss))) +
  theme_minimal() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray")  +
  geom_ribbon(aes(ymin=lwr, ymax=upr, x=preydiv_x1, fill = Speed, group = Speed), alpha = 0.5) +
  geom_line(size = 1, aes(color = Speed, group = Speed)) +
  scale_fill_viridis_d(option="rocket", breaks=c('Slow', 'Moderate', 'Fast'), labels = c('Slow', 'Moderate', 'Fast')) +
  scale_color_viridis_d(option="rocket", breaks=c('Slow', 'Moderate', 'Fast'), labels = c('Slow', 'Moderate', 'Fast')) +
  xlab("Prey diversity") +
  ylab("\nlog-RSS") +
  annotate("segment", x=-Inf, xend=Inf, y=-Inf, yend=-Inf, size = 1) +
  annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf, size = 1) +
  ggtitle("B)") +
  theme(legend.position = c(0.25, 0.86), text = element_text(size=14)) +
  xlim(0.55, 0.70) +
  ylim(-2.5, 2.5)

fig5c <- line_hmm +
  annotate("segment", x=-Inf, xend=Inf, y=-Inf, yend=-Inf, size = 1) +
  annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf, size = 1) +
  ggtitle("C)") +
  theme(legend.position = c(0.42, 0.86), text = element_text(size=14)) +
  ylab("\nState probabilities") 

tiff(file = "figures/asus_fig5.tiff", units="in", width=10, height=4, res=500)
plot_grid(fig5a, fig5b, fig5c, ncol = 3)
dev.off()
```

# Fig. 6
```{r}
fig6a <- p1 +
  geom_tile(data = newfish, aes(x = x,y = y, fill = rsf_prediction)) +
  scale_fill_viridis(option = "mako", name = "Predicted\nprobability", limits = c(0, 1), breaks = c(0.0, 0.5, 1)) +
  geom_sf(data = nat_trans, fill = "grey80", color = "white") + 
  coord_sf(xlim = ext(fish_raster)[1:2], ylim = ext(fish_raster)[3:4], expand = F) +
  theme(legend.key.height=unit(0.3,"cm"),
        legend.key.width = unit(0.4, "cm"),
        legend.direction = "horizontal",
        legend.position = c(0.80, 0.89)) +
  ggtitle("A) RSF") +
  ylab(" \n \n  ") + xlab("") +
  annotate("segment", x=-Inf, xend=Inf, y=-Inf, yend=-Inf, size = 1) +
  annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf, size = 1) +
  guides(fill = guide_colourbar(title.position="top", 
         title.hjust = 0.5), 
         size = guide_legend(title.position="top", title.hjust = 0.5))


fig6b <- p1 + 
  geom_tile(data = uds_ssf1, aes(x = x,y = y, fill = preydiv)) +
  scale_fill_viridis(option = "mako", name = "Predicted\nprobability", 
                     breaks = c(0,0.02,0.04), limits = c(0, 0.04)) +
  geom_sf(data = nat_trans, fill = "grey80", color = "white") + 
  coord_sf(xlim = ext(fish_raster)[1:2], ylim = ext(fish_raster)[3:4], expand = F) +
  theme(legend.key.height=unit(0.3,"cm"),
        legend.key.width = unit(0.4, "cm"),
        legend.direction = "horizontal",
        legend.position = c(0.80, 0.89)) +
  ggtitle("B) SSF without move-related covar") +
  ylab(" \n \n  ") + xlab("") +
  annotate("segment", x=-Inf, xend=Inf, y=-Inf, yend=-Inf, size = 1) +
  annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf, size = 1) +
  guides(fill = guide_colourbar(title.position="top", 
         title.hjust = 0.5), 
         size = guide_legend(title.position="top", title.hjust = 0.5))

fig6c <- p1 + 
  geom_tile(data = uds_ssf2, aes(x = x,y = y, fill = preydiv)) +
  scale_fill_viridis(option = "mako", name = "Predicted\nprobability", 
                     breaks = c(0,0.02,0.04), limits = c(0, 0.041)) +
  geom_sf(data = nat_trans, fill = "grey80", color = "white") + 
  coord_sf(xlim = ext(fish_raster)[1:2], ylim = ext(fish_raster)[3:4], expand = F) +
  theme(legend.key.height=unit(0.3,"cm"),
        legend.key.width = unit(0.4, "cm"),
        legend.direction = "horizontal",
        legend.position = c(0.80, 0.89)) +
  ggtitle("C) SSF with move-related covar") +
  ylab(" \n \n  ") + xlab("") +
  annotate("segment", x=-Inf, xend=Inf, y=-Inf, yend=-Inf, size = 1) +
  annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf, size = 1) +
  guides(fill = guide_colourbar(title.position="top", 
         title.hjust = 0.5), 
         size = guide_legend(title.position="top", title.hjust = 0.5))



fig6d <- p1 +
  geom_tile(data = newfish_long %>% filter(model == "hmm_state1"), 
            aes(x = x, y = y, fill = prediction)) +
  scale_fill_viridis(option = "mako", limits = c(0,1), breaks = c(0.0, 0.5, 1.0)) +
  labs(fill = 'Predicted\nprobability') +
  geom_sf(data = nat_trans, fill = "grey80", color = "white") + 
  coord_sf(xlim = ext(fish_raster)[1:2], ylim = ext(fish_raster)[3:4], expand = F) +
  theme(legend.key.height=unit(0.3,"cm"),
        legend.key.width = unit(0.4, "cm"),
        legend.direction = "horizontal",
        legend.position = c(0.80, 0.89)) +
  ggtitle("D) HMM state: Slow movement") +
  ylab(" \n \n  ") + xlab("") +
  annotate("segment", x=-Inf, xend=Inf, y=-Inf, yend=-Inf, size = 1) +
  annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf, size = 1) +
  guides(fill = guide_colourbar(title.position="top", 
         title.hjust = 0.5), 
         size = guide_legend(title.position="top", title.hjust = 0.5))

fig6e <- p1 +
  geom_tile(data = newfish_long %>% filter(model == "hmm_state2"), 
            aes(x = x, y = y, fill = prediction)) +
  scale_fill_viridis(option = "mako", limits = c(0,1), breaks = c(0.0, 0.5, 1.0)) +
  labs(fill = 'Predicted\nprobability') +
  geom_sf(data = nat_trans, fill = "grey80", color = "white") + 
  coord_sf(xlim = ext(fish_raster)[1:2], ylim = ext(fish_raster)[3:4], expand = F) +
  theme(legend.key.height=unit(0.3,"cm"),
        legend.key.width = unit(0.4, "cm"),
        legend.direction = "horizontal",
        legend.position = c(0.80, 0.89)) +
  ggtitle("E) HMM state: Moderate movement") +
  ylab(" \n \n  ") + xlab("") +
  annotate("segment", x=-Inf, xend=Inf, y=-Inf, yend=-Inf, size = 1) +
  annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf, size = 1) +
  guides(fill = guide_colourbar(title.position="top", 
         title.hjust = 0.5), 
         size = guide_legend(title.position="top", title.hjust = 0.5))

fig6f <- p1 +
  geom_tile(data = newfish_long %>% filter(model == "hmm_state3"), 
            aes(x = x, y = y, fill = prediction)) +
  scale_fill_viridis(option = "mako", limits = c(0,1), breaks = c(0.0, 0.5, 1.0)) +
  labs(fill = 'Predicted\nprobability') +
  geom_sf(data = nat_trans, fill = "grey80", color = "white") + 
  coord_sf(xlim = ext(fish_raster)[1:2], ylim = ext(fish_raster)[3:4], expand = F) +
  theme(legend.key.height=unit(0.3,"cm"),
        legend.key.width = unit(0.4, "cm"),
        legend.direction = "horizontal",
        legend.position = c(0.80, 0.89)) +
  ggtitle("F) HMM state: Fast movement") +
  ylab(" \n \n  ") + xlab("") +
  annotate("segment", x=-Inf, xend=Inf, y=-Inf, yend=-Inf, size = 1) +
  annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf, size = 1) +
  guides(fill = guide_colourbar(title.position="top", 
         title.hjust = 0.5), 
         size = guide_legend(title.position="top", title.hjust = 0.5))

tiff(file = "figures/asus_fig6.tiff", units="in", width=13, height = 8.5, res=300)
plot_grid(fig6a, fig6b, fig6c, fig6d, fig6e, fig6f, ncol = 3)
dev.off()
```


# Fig. S1
```{r}
## STEP LENGTH

# calculate frequencies of states
v <- momentuHMM::viterbi(hmm_trans_3)
stateFreq <- table(v) / length(v)

# plot colours
colours.states <- c("#99DDB6", "#539D9C", "#312C66")

# generate sequence for x axis of density functions
x <- seq(0, 50, length=1000)

# get converged mean and sd for each state 
meanARS <- hmm_trans_3$mle$step[1,1]  
sdARS <- hmm_trans_3$mle$step[2,1]    

meanCR <- hmm_trans_3$mle$step[1,2]    
sdCR <- hmm_trans_3$mle$step[2,2]     

meanTR <- hmm_trans_3$mle$step[1,3]    
sdTR <- hmm_trans_3$mle$step[2,3]    

# calculate shape and scale of the gamma distributions from mean and sd
sh <- function(mean, sd) { return(mean^2 / sd^2)}
sc <- function(mean, sd) { return(sd^2 / mean)}

# get density functions of the distributions
y_ARS <- dgamma(x, shape=sh(meanARS,sdARS),  scale=sc(meanARS,sdARS)) * stateFreq[[1]]
y_CR <- dgamma(x, shape=sh(meanCR,sdCR),  scale=sc(meanCR,sdCR)) * stateFreq[[2]]
y_TR <- dgamma(x, shape=sh(meanTR,sdTR),  scale=sc(meanTR,sdTR)) * stateFreq[[3]]


# combine densities in a single dataframe for more convenient plotting
df.y_ARS <- data.frame(dens=y_ARS, State="Foraging", x=x)
df.y_CR <- data.frame(dens=y_CR,  State="ARS", x=x)
df.y_TR <- data.frame(dens=y_TR,  State="Travelling", x=x)
statedis <- rbind(df.y_ARS, df.y_CR, df.y_TR)

# plot distributions
figS1a <- ggplot() +
  geom_line(data=statedis,aes(x=x,y=dens,colour=State,linetype=State), size=1.2) +
  scale_colour_manual(values=c(colours.states,"#000000"), 
              breaks = c('Foraging', 'ARS', 'Travelling'), 
              labels=c("Slow movement", "Moderate movement", "Fast movement")) +
  scale_linetype_manual(values=c("solid","solid", "solid"), 
              breaks = c('Foraging', 'ARS', 'Travelling'), 
              labels=c("Slow movement", "Moderate movement", "Fast movement")) +
  ylab("Density") + 
  xlab("Step length (kms)") +
  theme_minimal() +
  annotate("segment", x=-Inf, xend=Inf, y=-Inf, yend=-Inf, size = 1) +
  annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf, size = 1) +
  ggtitle("A)") +
  theme(text = element_text(size=14))



## TURNING ANGLE
# generate sequence for x axis of density functions
x <- seq(-pi, pi,length=1000)

# get converged mean and concentration for each state 
meanARS <- hmm_trans_3$mle$angle[1,1]  
sdARS <- hmm_trans_3$mle$angle[2,1]    

meanCR <- hmm_trans_3$mle$angle[1,2]    
sdCR <- hmm_trans_3$mle$angle[2,2]  

meanTR <- hmm_trans_3$mle$angle[1,3]    
sdTR <- hmm_trans_3$mle$angle[2,3]  

# get density functions of the distributions
y_ARS <- CircStats::dvm(x, mu=meanARS,  kappa=sdARS) * stateFreq[[1]]
y_CR <- CircStats::dvm(x, mu=meanCR,  kappa=sdCR) * stateFreq[[2]]
y_TR <- CircStats::dvm(x, mu=meanTR,  kappa=sdTR) * stateFreq[[3]]


# combine densities in a single dataframe for more convenient plotting
df.y_ARS <- data.frame(dens=y_ARS, State="Foraging",x=x)
df.y_CR <- data.frame(dens=y_CR,  State="ARS",x=x)
df.y_TR <- data.frame(dens=y_TR,  State="Travelling",x=x)

cmb <- rbind(df.y_TR, df.y_CR, df.y_ARS)

# plot distributions
figS1b <- ggplot() +
  geom_line(data=cmb,aes(x=x,y=dens,colour=State), size = 1.2) +
  scale_colour_manual(values=c(colours.states), breaks = c('Foraging', 'ARS', 'Travelling'), labels=c("Slow movement", "Moderate movement", "Fast movement")) +
  scale_x_continuous(limits=c(-pi,pi))+
  ylab("Density") + 
  xlab("Turn angle (radians) ") +
  theme_minimal() +
  annotate("segment", x=-Inf, xend=Inf, y=-Inf, yend=-Inf, size = 1) +
  annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf, size = 1) +
  ggtitle("B)") +
  theme(text = element_text(size=14))

tiff(file = "figures/asus_figS1.tiff", units="in", width=6, height = 8, res=500)
plot_grid(figS1a, figS1b, ncol = 1)
dev.off()

```




# Fig. S2
```{r}
#p1 <- read.csv("data/p1.csv", header = TRUE)
#p2 <- read.csv("data/p2.csv", header = TRUE)
  
figS2a <- fishmap +
  geom_sf(data = nat_trans, fill = "grey80", color = "white") + 
  coord_sf(xlim = ext(fish_raster)[1:2], ylim = ext(fish_raster)[3:4], expand = F) +
  geom_point(data = p1_burnt, aes(x = x_,y = y_), alpha = 0.61, color = "black") +
  geom_path(data = p1_burnt, aes(x = x_,y = y_), color = "black") +
  theme_minimal() +
  ggtitle("A) SSF1") +
  ylab(" \n \n  ") + xlab("") +
  annotate("segment", x=-Inf, xend=Inf, y=-Inf, yend=-Inf, size = 1) +
  annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf, size = 1) +
  theme(axis.text = element_blank(),
        axis.title.x = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        text = element_text(size=12),
        strip.background = element_rect(colour = "white"),
        legend.direction = "vertical", 
        legend.background = element_blank()) 


figS2b <- fishmap +
  geom_sf(data = nat_trans, fill = "grey80", color = "white") + 
  coord_sf(xlim = ext(fish_raster)[1:2], ylim = ext(fish_raster)[3:4], expand = F) +
  geom_point(data = p2_burnt, aes(x = x_,y = y_), alpha = 0.61, color = "black") +
  geom_path(data = p2_burnt, aes(x = x_,y = y_), color = "black") +
  theme_minimal() +
  ggtitle("B) SSF2") +
  ylab(" \n \n  ") + xlab("") +
  annotate("segment", x=-Inf, xend=Inf, y=-Inf, yend=-Inf, size = 1) +
  annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf, size = 1) +
  theme(axis.text = element_blank(),
        axis.title.x = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        text = element_text(size=12),
        strip.background = element_rect(colour = "white"),
        legend.direction = "vertical", 
        legend.background = element_blank()) 

tiff(file = "figures/asus_figS2.tiff", units="in", width=10, height = 4.5, res=500)
plot_grid(figS2a, figS2b, ncol = 2)
dev.off()
```

# Fig. S3
```{r}
# generate plot
figS3 <- ggplot(statianary_est, aes(x = cov, y = est, fill = state)) + 
  geom_ribbon(aes(ymin = lci, ymax = uci), alpha = 0.2) + 
  geom_line(aes(col = state), size = 1.5) + 
  scale_colour_manual(values=colours.states, breaks = c("Slow movement", "Moderate movement", "Fast movement"), labels=c("Slow movement", "Moderate movement", "Fast movement")) +
  scale_fill_manual(values=colours.states, breaks = c("Slow movement", "Moderate movement", "Fast movement"), labels=c("Slow movement", "Moderate movement", "Fast movement")) +
  ylab("State Probability") + 
  xlab("Prey Diversity") +
  theme_minimal() +
  annotate("segment", x=-Inf, xend=Inf, y=-Inf, yend=-Inf, size = 1) +
  annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf, size = 1) +
  ylab("\nState probabilities") 

tiff(file = "figures/asus_figS3.tiff", units="in", width=6, height = 4.5, res=500)
figS3
dev.off()
```

